### ISSUE TITLE
HTML a CSS - logo, ikona

### ISSUE THREAD

**Issue by tauchmanovaM** [SemStew/CMS_Django_B181#17]
Potřebovala bych pomoci se zobrazováním obrázků na webu. Nevím, proč se mi nezobrazuje logo v hlavičce a patičce, a ani ikona u záložky ve webovém prohlížeči.

**Comment by MarekSuchanek** [comment]
Zkus opravit cestu bez překlepu "imgages"...

https://github.com/SemStew/CMS_Django_B181/blob/de9099b59f2ef665fd35620cb0d3bf106a235035/SemStew/semstew/templates/semstew/base.html#L66

Jinak proč máte `SemStew/semstew/static/semstew` a `SemStew/semstew/templates/semstew`? Minimálně to poslední semstew je tam trochu zbytečný když už je to v Python modulu `semstew`...

**Comment by tauchmanovaM** [comment]
No to jsem vůl, jsem si toho překlepu nevšimla.

**Comment by tauchmanovaM** [comment]
Hotovo, už funguje. :)
