### ISSUE TITLE
Funkční požadavky - Evidence objednávek (UC6 - UC9)

### ISSUE THREAD

**Issue by tauchmanovaM** [SemStew/CMS_Django_B181#9]
Vytvoření funkcí na web pro UC6-UC9: Evidence objednávek. Zahrnují tyto body:                          

- [x] UC6: Vytvoření objednávky,
- [x] UC7: Přidání objednávky,
- [x] UC8: Upravení objednávky,
- [x] UC9: Smazání objednávky,

**Comment by tauchmanovaM** [comment]
Ty objednávky přesouvám do další iterace. To musíme probrat, jak to bylo vůbec myšleno.

**Comment by smolidav** [comment]
Přes admina

**Comment by tauchmanovaM** [comment]
Objednávky přes web do DB funguje pouze v admin sekci.. Nepodařilo se nám to korektně rozchodit.
